### ISSUE TITLE
Access keys assigned to an IAM user is limited to 2 

### ISSUE THREAD

**Issue by gonzalez** [rightscale/policy_templates#121]
### Policy Template Name
AWS Rotation Policy

### Issue Type
Access keys assigned to an IAM user is limited to 2 

 

### Policy Template version (Bug Only)
1.4

 

### Error Messages (Bug Only)
errorMessage": "Cannot exceed quota for AccessKeysPerUser: 2"

**Comment by MitchellGerdisch** [comment]
It's worth noting that the policy works as-is.
When the error occurs, the policy takes action to delete a key and then create the new key.
However, it is understood that the error that is generated in AWS by the failed request is confusing.
So the plan is to update the policy to avoid this error.

**Comment by MitchellGerdisch** [comment]
Solved by PR: https://github.com/rightscale/policy_templates/pull/122
