### ISSUE TITLE
Idle Load Balancers  

### ISSUE THREAD

**Issue by gonzalez** [rightscale/policy_templates#157]
Checks your Elastic Load Balancing configuration for load balancers that are not actively used. Any load balancer that is configured accrues charges. If a load balancer has no associated back-end instances or if network traffic is severely limited, the load balancer is not being used effectively.

**Comment by rshade** [comment]
We have this policy at: https://github.com/rightscale/policy_templates/tree/master/cost/aws/elb/clb_unused
