### ISSUE TITLE
Unassociated Elastic IP Addresses  

### ISSUE THREAD

**Issue by gonzalez** [rightscale/policy_templates#159]
Checks for Elastic IP addresses (EIPs) that are not associated with a running Amazon Elastic Compute Cloud (Amazon EC2) instance. EIPs are static IP addresses designed for dynamic cloud computing. Unlike traditional static IP addresses, EIPs can mask the failure of an instance or Availability Zone by remapping a public IP address to another instance in your account. A nominal charge is imposed for an EIP that is not associated with a running instance.

**Comment by rshade** [comment]
We have this at: https://github.com/rightscale/policy_templates/tree/master/cost/unattached_addresses
