### ISSUE TITLE
Error on sched report  policy

### ISSUE THREAD

**Issue by ryanoleary** [rightscale/policy_templates#175]
### Policy Template Name
Scheduled Report

### Issue Type
Bug

### Policy Template version (Bug Only)
1.1

### Error Messages (Bug Only)
Summary:
  failed to retrieve datasource data
Detail:
  unexpected response status
  POST https://optima.rightscale.com/bill-analysis/orgs/6698/costs/aggregated
  got "400 Bad Request", expected a status in the 200 range
  response body:
  {"id":"mxgWKvhV","code":"bad_request","status":400,"detail":"startAt \"2019-02-04\" must be before endAt \"2019-02-04\""}
  
Location:
  datasource "ds_report"
    script "js_report"
      argument "current_week_costs"
        datasource "current_week_costs"

**Comment by ryanoleary** [comment]
The policy ran again on its own and ran fine. Not sure under what conditions that error occurs.

**Comment by srpomeroy** [comment]
@ryanoleary Happens on Mondays. Working on a fix.
