### ISSUE TITLE
Readme link in sched report policy is wrong

### ISSUE THREAD

**Issue by ryanoleary** [rightscale/policy_templates#176]
### Policy Template Name
Scheduled Report

### Issue Type
Bug

### Policy Template version (Bug Only)
1.1

### Code Snippet (Bug Only)
Readme link in description is wrong (missing a trailing 's'): 
See [README](https://github.com/rightscale/policy_templates/tree/master/cost/scheduled_report) for more details"

**Comment by srpomeroy** [comment]
Addressed in #177
