### ISSUE TITLE
Every policy should have the required permissions sufficiently documented

### ISSUE THREAD

**Issue by ryanoleary** [rightscale/policy_templates#191]
### Policy Template Name
All

### Issue Type
Feature Request

### Use Case (Feature Request -or- New Policy Template Request Only)
The ask is to clearly document the required permissions/roles/privileges/etc required in order for each policy to run, and specifically to NOT talk about the general "policy" roles that are required to use the policy manager (since those are always the same and should be addressed in other docs).

For policy-specific roles, the privileges required might sometimes be RS roles, in which case we'd need to specify the role and the scope at which the role is required (org, account, BC, etc). Or the roles might be cloud (or other API) specific roles, such as a specific IAM privilege for AWS.

**Comment by srpomeroy** [comment]
What are everyones thoughts on how/where it should be documented? Initial thought from me is in the readme for each policy in GitHub. But does that make sense? Comments in the code itself?

**Comment by rshade** [comment]
Tracked Internally as POL-66
