### ISSUE TITLE
Add "exclude or do-not-delete" tag support in relevant policies 

### ISSUE THREAD

**Issue by bharatrightscale** [rightscale/policy_templates#40]
### Policy Template Name

Allow users to specify a way to exclude resources from policy actions by specifying a exclude tag. e.g.: do_not_delete sort of tag on UAVs.

This would be an additional input parameter field in policy templates.

### Issue Type
[Bug -or- Feature Request -or- New Policy Template Request]

### Use Case (Feature Request -or- New Policy Template Request Only)
[Describe the use case for this feature request or new policy template request]

### Policy Template version (Bug Only)
[Version of Policy Template in use, this can be found in the long_description]

### Code Snippet (Bug Only)
[Please provide any relevant code snippets (ie. datasource,escalation,policy, RCL, etc.) as it relates to the bug]

### Error Messages (Bug Only)
[Provide any error messages returned (if applicable)]

**Comment by MitchellGerdisch** [comment]
Fixed by https://github.com/rightscale/policy_templates/pull/70
