### ISSUE TITLE
Add clear documentation to help users with IAM policy and creds requirement for RI policies

### ISSUE THREAD

**Issue by bharatsinghgithub** [rightscale/policy_templates#43]
### Policy Template Name

As per the discussion on slack, we should make sure RI policies README have sufficient information for a noob user to get started. The discussed solution was to leverage CM creds along with IAM access needed for RS to fetch RI purchase and coverage info from the CE API.

https://github.com/rightscale/policy_templates/tree/master/cost/aws/reserved_instances

### Issue Type
[Bug -or- Feature Request -or- New Policy Template Request]

### Use Case (Feature Request -or- New Policy Template Request Only)
[Describe the use case for this feature request or new policy template request]

### Policy Template version (Bug Only)
[Version of Policy Template in use, this can be found in the long_description]

### Code Snippet (Bug Only)
[Please provide any relevant code snippets (ie. datasource,escalation,policy, RCL, etc.) as it relates to the bug]

### Error Messages (Bug Only)
[Provide any error messages returned (if applicable)]

**Comment by rshade** [comment]
Tracked Internally as POL-66
