### ISSUE TITLE
Downsize Policy does not work for Windows Servers

### ISSUE THREAD

**Issue by MitchellGerdisch** [rightscale/policy_templates#63]
### Policy Template Name
"Downsize Instances Policy Template"

### Issue Type
RL10 monitoring for Windows Servers does not report a "total memory" value like it does for Linux.
The policy template has a datasource based on grabbing total memory for applicable instances by using the "total memory" metric.
When it encounters a windows server the datasource fails and the policy fails.

### Use Case (Feature Request -or- New Policy Template Request Only)
[Describe the use case for this feature request or new policy template request]

### Policy Template version (Bug Only)
1.4

### Code Snippet (Bug Only)
https://github.com/rightscale/policy_templates/blob/2c40554f25ef5fa15a1121301f0e581dc398f4ef/cost/downsize_instance/downsize-instance.pt#L202

datasource "ds_instance_metrics_total_memory" do
  iterate($ds_filtered_instances)
  request do
    auth $auth_rs
    host rs_cm_host
    path join([val(iter_item,"href"), "/monitoring_metrics/memory:memory-total/data"])
    query "start", "-300"
    query "end", "0"
    header "X-API-Version", "1.5"
  end
  result do
    field "href",        val(iter_item,"href")
    field "memory_data_points", jmes_path(response, "variables_data[0].points[*]")
    field "resource_uid",          val(iter_item,"resource_uid")
    field "instance_type",        val(iter_item,"instance_type")
    field "name",        val(iter_item,"name")
  end
end

### Error Messages (Bug Only)
Summary:
  failed to retrieve datasource data
Detail:
  unexpected response status
  got "422 Unprocessable Entity", expected a status in the 200 range
  response body:
  MonitoringDataError: Unable to retrieve monitoring data.
Location:
  datasource "ds_instances_with_calculated_metrics"
    script "js_calculate_metrics"
      argument "instance_metrics_total_memory"
        datasource "ds_instance_metrics_total_memory"

**Comment by rshade** [comment]
rshade [10:28 AM]
http://reference.rightscale.com/api1.6/index.html#/1.6/controller/V1_6-Definitions-InstanceTypes

**Comment by srpomeroy** [comment]
The COS utilization script reports on the metrics properly for Windows and Linux. It may be of help https://github.com/rs-services/cos_assets/blob/master/RightLink_Utilization/Get-OrgUtilizationData.ps1

**Comment by cdwilhelm** [comment]
@bryankaraffa this is now resolved
