### ISSUE TITLE
README update for policy upload script

### ISSUE THREAD

**Issue by bharatrightscale** [rightscale/policy_templates#66]
### Policy Template Name

The README could use some work to clearly explain steps and what is happening if the users run the script. Right now it talks more about the technicality vs process. Just my 2 cents.

https://github.com/rightscale/policy_templates/tree/master/tools/policy_upload_scripts

### Issue Type
[Bug -or- Feature Request -or- New Policy Template Request]

### Use Case (Feature Request -or- New Policy Template Request Only)
[Describe the use case for this feature request or new policy template request]

### Policy Template version (Bug Only)
[Version of Policy Template in use, this can be found in the long_description]

### Code Snippet (Bug Only)
[Please provide any relevant code snippets (ie. datasource,escalation,policy, RCL, etc.) as it relates to the bug]

### Error Messages (Bug Only)
[Provide any error messages returned (if applicable)]

**Comment by MitchellGerdisch** [comment]
Addressed by the merged PR:
https://github.com/rightscale/policy_templates/pull/68
