### ISSUE TITLE
UAV policy enhancement: Add "last attached to" and "tags" to the UAV policy

### ISSUE THREAD

**Issue by bharatsinghgithub** [rightscale/policy_templates#78]
### Policy Template Name

The request came from Jim @ CIBC who is interested in seeing the 2 fields: last attached to and tags in the UAV policy. 

### Issue Type

Feature Request

### Use Case (Feature Request -or- New Policy Template Request Only)
[Describe the use case for this feature request or new policy template request]

### Policy Template version (Bug Only)

1.4

### Code Snippet (Bug Only)
[Please provide any relevant code snippets (ie. datasource,escalation,policy, RCL, etc.) as it relates to the bug]

### Error Messages (Bug Only)
[Provide any error messages returned (if applicable)]

**Comment by MitchellGerdisch** [comment]
There is no way to know what a volume was last attached to.
Also the only tags that are supported for volumes (currently) are RightScale level tags.

Therefore, the "last attached to" part of the issue will not be implemented.
And, the "tags" part of the issue will only reflect RightScale tags.

**Comment by bharatrightscale** [comment]
Cool thanks.

**Comment by cdwilhelm** [comment]
closing, already updated
